version: 2
sources:
  - name: tpch_sf1
    database: SNOWFLAKE_SAMPLE_DATA  
    schema: TPCH_SF1  
    tables:      
     - name: customer      
     - name: orders      
     - name: lineitem
models:
  - name: stg_customer
    description: "Staging de CUSTOMER"
    columns:      
      - name: c_custkey
        tests:          
          - not_null
          - unique