version: 2
sources:
  - name: tpch_sf1kkk
    database: SNOWFLAKE_SAMPLE_DATA  
    schema: TPCH_SF1  
    tables:      
     - name: customer      
     - name: orders      
     - name: lineitem
models:
  - name: hub_customer
    description: "Hub de CUSTOMER"
    columns:      
      - name: c_custkey
        tests:          
          - not_null
          - unique